coverage:
  status:
    project:
        default: yes
        threshold: 0.5
        base: pr
    patch: 
        default: yes
        threshold: 0.5
        base: pr
ignore:
    - "cloudsync/providers/box.py"
    - "cloudsync/providers/dropbox.py"
    - "cloudsync/providers/filesystem.py"
