coverage:
  range: "80...100"
  status:
    project:
        default: yes
        base: pr
    patch: 
        default: yes
        base: pr
ignore:
    - "cloudsync/providers"
    - "cloudsync/tests/providers"
